import Footer from "@/components/footer/Footer";
import Navbar from "@/components/navbar/Navbar";
import { Inter } from "next/font/google";
import styles from "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Portfilio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <div className={styles.container}>
          <Navbar />

          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
